grpc:
  client:
    file-upload:
      address: "static://localhost:9090"
      negotiationType: plaintext
    file-operations:
      address: "static://localhost:9090"
      negotiationType: plaintext
bootstrap:
  url: ${BOOTSTRAP_URL:http://localhost:8085}



spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_name}
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:db_password}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /client


jwt:
    secret: secret

